export const SET_HEADER_LINKS = 'SET_HEADER_LINKS';
export const SET_NAVBAR_LINKS = 'SET_NAVBAR_LINKS';
export const CHANGE_NAVBAR_ACTIVE = 'CHANGE_NAVBAR_ACTIVE';
export const FETCH_EXPERIENCES = 'FETCH_EXPERIENCES';
export const TOGGLE_DESCRIPTION = 'TOGGLE_DESCRIPTION';